[tox]
env_list = py39, flake8
skip_missing_interpreters = true

; Legacy travis section removed (not used with tox 4)

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 src tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}

commands = python -m unittest discover
